spring:
  application:
    name: chessora
    
  frontend:
    url: http://localhost:5173
    
  jwt:
    secret: keymySuperSecurekey1298371298739821739871298739812739879key
    expirationMs: 172800000
    

  datasource:
    url: jdbc:h2:mem:chessora
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      
  jpa:
    hibernate:
      ddl-auto: create-drop